# Generated by Django 3.1.5 on 2021-01-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='label',
            field=models.CharField(default='', max_length=30),
        ),
    ]
