# Generated by Django 3.1.5 on 2021-01-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210127_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
